services:
  db:
    container_name: ofs_db
    image: mysql:8.3.0
    volumes:
      - ./db:/var/lib/mysql
      - ./ofs_dump.sql:/docker-entrypoint-initdb.d/ofs_dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ofs
    ports:
        - 3306:3306
  web:
    container_name: ofs_web
    build: .
    depends_on:
      - db
    image: tomcat:9.0.88
    volumes:
      - ./target/CS160_Project-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/CS160_Project-1.0-SNAPSHOT.war
    ports:
        - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ofs

volumes:
  db: